//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_Osiguranje.Models
{
    using System;

    public partial class CK_Rizik
    {
        public decimal Id_CK_Rizik { get; set; }
        public decimal Id_Rizik { get; set; }
        public Nullable<decimal> Koeficijent_CK_Rizik { get; set; }
        public Nullable<decimal> Cena_CK_Rizik { get; set; }
        public System.DateTime Datum_pocetka_vazenja_CL_Rizik { get; set; }
    
        public virtual Rizik Rizik { get; set; }
    }
}
