//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_Osiguranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDV
    {
        public PDV()
        {
            this.Realizacija_osiguranja = new HashSet<Realizacija_osiguranja>();
            this.Stopa_PDV = new HashSet<Stopa_PDV>();
        }
    
        public short Id_PDV { get; set; }
        public string Naziv_PDV { get; set; }
    
        public virtual ICollection<Realizacija_osiguranja> Realizacija_osiguranja { get; set; }
        public virtual ICollection<Stopa_PDV> Stopa_PDV { get; set; }
    }
}
