//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_Osiguranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prevod
    {
        public int Id_Prevod { get; set; }
        public decimal Id_Rizik { get; set; }
        public short Id_Jezik { get; set; }
        public string Naziv_Prevod { get; set; }
    
        public virtual Jezik Jezik { get; set; }
        public virtual Rizik Rizik { get; set; }
    }
}
