//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_Osiguranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realizacija_osiguranja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Realizacija_osiguranja()
        {
            this.Stavka_u_realizaciji = new HashSet<Stavka_u_realizaciji>();
        }
    
        public int Id_Realizacija_osiguranja { get; set; }
        public short Id_PDV { get; set; }
        public Nullable<System.DateTime> Datum_Realizacija_osiguranja { get; set; }
        public Nullable<decimal> Vrednost_Realizacija_osiguranja { get; set; }
        public Nullable<decimal> Vrednost_PDV_Realizacija_osiguranja { get; set; }
        public Nullable<decimal> Ukupna_vrednost_Realizacija_osiguranja { get; set; }
        public System.DateTime Datum_od { get; set; }
        public System.DateTime Datum_do { get; set; }
    
        public virtual PDV PDV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_u_realizaciji> Stavka_u_realizaciji { get; set; }
    }
}
