//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_Osiguranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rizik_za_osigurani_entitet
    {
        public int Id_Rizik_za_osigurani_entitet { get; set; }
        public Nullable<int> Id_Stavka_u_realizaciji { get; set; }
        public Nullable<decimal> Id_Rizik { get; set; }
    
        public virtual Rizik Rizik { get; set; }
        public virtual Stavka_u_realizaciji Stavka_u_realizaciji { get; set; }
    }
}
