//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_Osiguranje.Models
{
    using System;

    public partial class Stopa_PDV
    {
        public short Id_Stopa_PDV { get; set; }
        public Nullable<short> Id_PDV { get; set; }
        public decimal Stopa_PDV1 { get; set; }
        public System.DateTime Datum_pocetka_vazenja_Stopa_PDV { get; set; }
    
        public virtual PDV PDV { get; set; }
    }
}
