//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_Osiguranje.Models
{
    using System.Collections.Generic;

    public partial class Tip_osiguranja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tip_osiguranja()
        {
            this.Vrsta_rizika = new HashSet<Vrsta_rizika>();
        }
    
        public decimal Id_Tip_osiguranja { get; set; }
        public string Naziv_Tip_osiguranja { get; set; }
        public string Opis_Tip_osiguranja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vrsta_rizika> Vrsta_rizika { get; set; }
    }
}
