//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_Osiguranje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vrsta_rizika
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vrsta_rizika()
        {
            this.Rizik = new HashSet<Rizik>();
        }
    
        public decimal Id_Vrsta_rizika { get; set; }
        public decimal Id_Tip_osiguranja { get; set; }
        public string Naziv_Vrsta_rizika { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rizik> Rizik { get; set; }
        public virtual Tip_osiguranja Tip_osiguranja { get; set; }
    }
}
